// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    IEpE: typeof import('~icons/ep/e')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    Login: typeof import('./../components/core/login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
